//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/_Project/Assets/InputActions/InputViewActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace VTTRPG.Inputs
{
    public partial class @InputViewActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputViewActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputViewActions"",
    ""maps"": [
        {
            ""name"": ""Popups"",
            ""id"": ""0e0e2cd8-6a05-4a12-be79-e6fbaab036d2"",
            ""actions"": [
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""d715b6fb-7051-4a72-a1d8-e0419cb6a407"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7cf07a4-d7ca-436e-b8f3-93a127de2c46"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Popups
            m_Popups = asset.FindActionMap("Popups", throwIfNotFound: true);
            m_Popups_Close = m_Popups.FindAction("Close", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Popups
        private readonly InputActionMap m_Popups;
        private IPopupsActions m_PopupsActionsCallbackInterface;
        private readonly InputAction m_Popups_Close;
        public struct PopupsActions
        {
            private @InputViewActions m_Wrapper;
            public PopupsActions(@InputViewActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Close => m_Wrapper.m_Popups_Close;
            public InputActionMap Get() { return m_Wrapper.m_Popups; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PopupsActions set) { return set.Get(); }
            public void SetCallbacks(IPopupsActions instance)
            {
                if (m_Wrapper.m_PopupsActionsCallbackInterface != null)
                {
                    @Close.started -= m_Wrapper.m_PopupsActionsCallbackInterface.OnClose;
                    @Close.performed -= m_Wrapper.m_PopupsActionsCallbackInterface.OnClose;
                    @Close.canceled -= m_Wrapper.m_PopupsActionsCallbackInterface.OnClose;
                }
                m_Wrapper.m_PopupsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Close.started += instance.OnClose;
                    @Close.performed += instance.OnClose;
                    @Close.canceled += instance.OnClose;
                }
            }
        }
        public PopupsActions @Popups => new PopupsActions(this);
        public interface IPopupsActions
        {
            void OnClose(InputAction.CallbackContext context);
        }
    }
}
